---
- name: Remove and Run Docker Container
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Stop existing container (if it exists)
      command: docker stop helloapp
      ignore_errors: true

    - name: Remove existing container (if it exists)
      command: docker rm helloapp
      ignore_errors: true

    - name: Pull latest Docker image
      command: docker pull minhtrang2106/hellogo
      ignore_errors: true

    - name: Run a new container
      command: docker run -d -p 8085:8080 --name helloapp --rm minhtrang2106/hellogo
